### ISSUE TITLE
perl Build.pl errors

### ISSUE THREAD

**Issue by rviana** [Morgan-Stanley/venn-core#1]
Instructions indicate to run $ perl Build.pl, however it errors...

$ git clone https://github.com/Morgan-Stanley/venn-core.git
$ cd venn-core
$ perl Build.PL 
Can't locate Venn/LocalBuild.pm in @INC (you may need to install the Venn::LocalBuild module) (@INC contains: lib /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at Build.PL line 9.

How do I obtain LocalBuild.pm?

**Comment by RyanKupfer** [comment]
These modules should be optional. I'll take a look at fixing the "use" calls. Thanks!
