### ISSUE TITLE
Another experimental feature warning with perl 5.20

### ISSUE THREAD

**Issue by wphillipmoore** [Morgan-Stanley/venn-core#15]
This one's new to me ('cause I don't use push to a reference anywhere), but when the tests run with perl5.20:

2015/08/27 09:45:22 push on reference is experimental at /var/tmp/venn-core-1.0.0-build011-build/x86-64.rhel.7/5.20/source/core-1.0.0/t/../lib/Venn/PlacementEngine.pm line 196.

I'll look for a similar 'no warnings' line that can shut this one up, unless you want to drop the use of the syntax.   I don't know the history here (yet), but I suspect it's similar to the fate of smartmatch.

**Comment by wphillipmoore** [comment]
Interesting discussion about it at:

http://stackoverflow.com/questions/31466854/perl-experimental-features-and-perldoc

And as this commit shows:

http://perl5.git.perl.org/perl.git/commit/262309092c2de925e7ae4a527174f8dc2a0ec7b7

It's about to go away, so in order to future proof the code, the use of this feature needs to be dropped.  Patch to follow shortly....

**Comment by RyanKupfer** [comment]
Addressed by #17
