### ISSUE TITLE
Compile fails due to missing files in root/swagger

### ISSUE THREAD

**Issue by wphillipmoore** [Morgan-Stanley/venn-core#5]
After building the 350+ CPAN dependencies required for this distribution, I got a little further, but it looks like you are missing some content from the public distribution:

[2015-08-07 16:08:57]  Can't copy('root/swagger/api-docs.json', 'blib/root/swagger/api-docs.json'): No such file or directory at /efs/dist/perl5/core/5.20.2-build003/.exec/x86-64.rhel.6/lib/perl5/Module/Build/Base.pm line 5643.

This file is not present under root/swagger.

**Comment by RyanKupfer** [comment]
Can you try running sbin/generate_swagger_documentation.pl ? This should definitely be in the README.md or INSTALL file.

**Comment by RyanKupfer** [comment]
It's now hooked into the Build.PL script so core's documentation is automatically generated.

**Comment by RyanKupfer** [comment]
Addressed by #6
